# -*- coding: utf-8 -*-
"""Introdução à Machine Learning e Classificação

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s773aH4TRtwdHQIjbgJ5mJCvAKXP5sI4

### <font color = blue> Para o desenvolvimento desses projetos utilizaremos o pandas para explorar os dados de maneira descritiva e o seaborn para explorar de maneira visual

# <font color= green>Primeiro Projeto de Classificação
---
#### Nesse primeiro projeto vamos fazer a classificação dos dados entre porco e cachorro, apenas para aprender o básico, dando início ao aprendizado
"""

# Features: pelo longo, perna curta e faz "au au". (1 == sim, 0 == não)

porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

# 1 => porco, 0 => cachorro
treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1,1,1,0,0,0] #label / etiqueta

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(treino_x, treino_y)

animal_misterioso = [1,1,1]
model.predict([animal_misterioso])

misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0,1,1]

previsoes = model.predict(teste_x)
previsoes

corretos = (previsoes == teste_y).sum()
total = len(teste_x)
taxa_de_acerto = corretos/total
print("A taxa de acertos é:",taxa_de_acerto * 100)

from sklearn.metrics import accuracy_score

taxa_de_acerto = accuracy_score(teste_y, previsoes)
print("Taxa de acerto de:", taxa_de_acerto * 100)

